import { sql, type Kysely } from 'kysely';

/**
 * Initial schema. Written in the portable SQL subset that works identically
 * on SQLite and Postgres: TEXT / INTEGER / REAL columns, text ids, ISO-8601
 * text timestamps, integer 0|1 booleans, JSON stored as TEXT.
 */
const STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    password_hash TEXT,
    role TEXT NOT NULL DEFAULT 'owner',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS workspaces (
    id TEXT PRIMARY KEY,
    owner_user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS source_accounts (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    category TEXT NOT NULL,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'connected',
    auth_ref TEXT,
    scopes TEXT NOT NULL DEFAULT '[]',
    capabilities TEXT NOT NULL DEFAULT '[]',
    settings TEXT NOT NULL DEFAULT '{}',
    last_sync_at TEXT,
    sync_cursor TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_source_accounts_ws ON source_accounts (workspace_id)`,
  `CREATE TABLE IF NOT EXISTS source_items (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    category TEXT NOT NULL,
    external_id TEXT NOT NULL,
    dedupe_key TEXT,
    title TEXT NOT NULL,
    body_text TEXT,
    snippet TEXT,
    sender TEXT,
    participants TEXT NOT NULL DEFAULT '[]',
    item_timestamp TEXT NOT NULL,
    due_at TEXT,
    starts_at TEXT,
    ends_at TEXT,
    url TEXT,
    thread_external_id TEXT,
    project_ids TEXT NOT NULL DEFAULT '[]',
    people_ids TEXT NOT NULL DEFAULT '[]',
    labels TEXT NOT NULL DEFAULT '[]',
    raw_metadata TEXT NOT NULL DEFAULT '{}',
    provenance TEXT NOT NULL DEFAULT '{}',
    is_read INTEGER NOT NULL DEFAULT 0,
    content_hash TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (account_id, external_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_source_items_ws_ts ON source_items (workspace_id, item_timestamp)`,
  `CREATE INDEX IF NOT EXISTS idx_source_items_ws_cat ON source_items (workspace_id, category)`,
  `CREATE INDEX IF NOT EXISTS idx_source_items_dedupe ON source_items (dedupe_key)`,
  `CREATE TABLE IF NOT EXISTS source_attachments (
    id TEXT PRIMARY KEY,
    item_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    mime_type TEXT,
    size_bytes INTEGER,
    external_ref TEXT,
    storage_path TEXT,
    text_extracted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_source_attachments_item ON source_attachments (item_id)`,
  `CREATE TABLE IF NOT EXISTS people (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    emails TEXT NOT NULL DEFAULT '[]',
    handles TEXT NOT NULL DEFAULT '[]',
    organization_id TEXT,
    title TEXT,
    importance TEXT NOT NULL DEFAULT 'normal',
    is_self INTEGER NOT NULL DEFAULT 0,
    interaction_count INTEGER NOT NULL DEFAULT 0,
    last_interaction_at TEXT,
    notes TEXT,
    origin TEXT NOT NULL DEFAULT 'observed',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_people_ws ON people (workspace_id)`,
  `CREATE TABLE IF NOT EXISTS organizations (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    domains TEXT NOT NULL DEFAULT '[]',
    notes TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    priority TEXT NOT NULL DEFAULT 'normal',
    keywords TEXT NOT NULL DEFAULT '[]',
    stakeholder_people_ids TEXT NOT NULL DEFAULT '[]',
    due_at TEXT,
    origin TEXT NOT NULL DEFAULT 'user',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_projects_ws ON projects (workspace_id)`,
  `CREATE TABLE IF NOT EXISTS task_candidates (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    source_item_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'open',
    due_at TEXT,
    deferred_until TEXT,
    importance_score REAL NOT NULL DEFAULT 0,
    urgency_score REAL NOT NULL DEFAULT 0,
    effort_score REAL NOT NULL DEFAULT 0,
    overall_score REAL NOT NULL DEFAULT 0,
    priority_level TEXT NOT NULL DEFAULT 'medium',
    urgency_level TEXT NOT NULL DEFAULT 'medium',
    effort_level TEXT NOT NULL DEFAULT 'medium',
    planning_category TEXT NOT NULL DEFAULT 'follow_up',
    signals TEXT NOT NULL DEFAULT '[]',
    explanation TEXT,
    recommended_action TEXT,
    project_id TEXT,
    people_ids TEXT NOT NULL DEFAULT '[]',
    origin TEXT NOT NULL DEFAULT 'scoring',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_task_candidates_ws_status ON task_candidates (workspace_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_task_candidates_ws_score ON task_candidates (workspace_id, overall_score)`,
  `CREATE TABLE IF NOT EXISTS digests (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'manual',
    status TEXT NOT NULL DEFAULT 'generating',
    generated_at TEXT,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    summary_markdown TEXT,
    plan_markdown TEXT,
    model_used TEXT,
    stats TEXT NOT NULL DEFAULT '{}',
    supersedes_digest_id TEXT,
    error TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_digests_ws_created ON digests (workspace_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS digest_items (
    id TEXT PRIMARY KEY,
    digest_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    source_item_id TEXT,
    task_candidate_id TEXT,
    title TEXT NOT NULL,
    source_label TEXT NOT NULL,
    source_category TEXT,
    item_timestamp TEXT,
    section TEXT NOT NULL,
    planning_category TEXT NOT NULL,
    priority_level TEXT NOT NULL,
    urgency_level TEXT NOT NULL,
    effort_level TEXT NOT NULL,
    recommended_action TEXT,
    explanation TEXT NOT NULL,
    signals TEXT NOT NULL DEFAULT '[]',
    rank INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_digest_items_digest ON digest_items (digest_id)`,
  `CREATE TABLE IF NOT EXISTS user_preferences (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL DEFAULT 'null',
    kind TEXT NOT NULL DEFAULT 'explicit',
    origin TEXT NOT NULL DEFAULT 'user',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (user_id, key)
  )`,
  `CREATE TABLE IF NOT EXISTS memory_entries (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    content TEXT NOT NULL,
    origin TEXT NOT NULL DEFAULT 'explicit',
    confidence REAL NOT NULL DEFAULT 1,
    enabled INTEGER NOT NULL DEFAULT 1,
    related_people_ids TEXT NOT NULL DEFAULT '[]',
    related_project_ids TEXT NOT NULL DEFAULT '[]',
    provenance TEXT NOT NULL DEFAULT '{}',
    last_used_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_memory_ws_enabled ON memory_entries (workspace_id, enabled)`,
  `CREATE TABLE IF NOT EXISTS permission_policies (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    capability TEXT NOT NULL,
    effect TEXT NOT NULL,
    scope TEXT NOT NULL DEFAULT '{}',
    description TEXT,
    created_by TEXT NOT NULL DEFAULT 'user',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_policies_ws ON permission_policies (workspace_id)`,
  `CREATE TABLE IF NOT EXISTS approval_requests (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    agent_action_id TEXT NOT NULL,
    capability TEXT NOT NULL,
    action_type TEXT NOT NULL,
    target_provider TEXT,
    target_account_id TEXT,
    target_ref TEXT NOT NULL DEFAULT '{}',
    risk_level TEXT NOT NULL,
    reason TEXT NOT NULL,
    preview TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'pending',
    requested_at TEXT NOT NULL,
    decided_at TEXT,
    decision_note TEXT,
    conversation_id TEXT,
    expires_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_approvals_ws_status ON approval_requests (workspace_id, status)`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT,
    event_type TEXT NOT NULL,
    actor TEXT NOT NULL,
    capability TEXT,
    target_type TEXT,
    target_id TEXT,
    summary TEXT NOT NULL,
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_audit_ws_created ON audit_logs (workspace_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_ws_event ON audit_logs (workspace_id, event_type)`,
  `CREATE TABLE IF NOT EXISTS conversations (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    pinned INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    last_message_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_conversations_ws ON conversations (workspace_id, last_message_at)`,
  `CREATE TABLE IF NOT EXISTS messages (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    citations TEXT NOT NULL DEFAULT '[]',
    suggested_actions TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'complete',
    model_used TEXT,
    llm_call_id TEXT,
    error TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_messages_conv ON messages (conversation_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS uploaded_files (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    account_id TEXT,
    source_item_id TEXT,
    filename TEXT NOT NULL,
    mime_type TEXT,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    storage_path TEXT NOT NULL,
    text_extracted INTEGER NOT NULL DEFAULT 0,
    extraction_error TEXT,
    status TEXT NOT NULL DEFAULT 'processing',
    sha256 TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_uploaded_files_ws ON uploaded_files (workspace_id)`,
  `CREATE TABLE IF NOT EXISTS connector_runs (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'incremental',
    status TEXT NOT NULL DEFAULT 'running',
    started_at TEXT NOT NULL,
    completed_at TEXT,
    items_seen INTEGER NOT NULL DEFAULT 0,
    items_created INTEGER NOT NULL DEFAULT 0,
    items_updated INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    errors TEXT NOT NULL DEFAULT '[]',
    cursor_before TEXT,
    cursor_after TEXT,
    log TEXT,
    triggered_by TEXT NOT NULL DEFAULT 'manual',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_connector_runs_account ON connector_runs (account_id, started_at)`,
  `CREATE TABLE IF NOT EXISTS llm_provider_configs (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    base_url TEXT,
    model TEXT NOT NULL,
    api_key_env TEXT,
    api_key_encrypted TEXT,
    temperature REAL,
    max_tokens INTEGER,
    timeout_ms INTEGER,
    extra_headers TEXT NOT NULL DEFAULT '{}',
    enabled INTEGER NOT NULL DEFAULT 1,
    is_local INTEGER NOT NULL DEFAULT 0,
    supports_embeddings INTEGER NOT NULL DEFAULT 0,
    embedding_model TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS llm_task_routes (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    task TEXT NOT NULL,
    provider_config_id TEXT,
    model_override TEXT,
    params TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE (workspace_id, task)
  )`,
  `CREATE TABLE IF NOT EXISTS llm_call_logs (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT,
    provider_config_id TEXT,
    provider_kind TEXT NOT NULL,
    model TEXT NOT NULL,
    task TEXT NOT NULL,
    status TEXT NOT NULL,
    latency_ms INTEGER NOT NULL DEFAULT 0,
    input_tokens INTEGER,
    output_tokens INTEGER,
    error TEXT,
    request_summary TEXT NOT NULL DEFAULT '{}',
    purpose_ref TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_llm_calls_ws_created ON llm_call_logs (workspace_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS retrieval_chunks (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    ref_id TEXT NOT NULL,
    chunk_index INTEGER NOT NULL DEFAULT 0,
    text TEXT NOT NULL,
    metadata TEXT NOT NULL DEFAULT '{}',
    created_at TEXT NOT NULL,
    UNIQUE (source_type, ref_id, chunk_index)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_chunks_ws_type ON retrieval_chunks (workspace_id, source_type)`,
  `CREATE TABLE IF NOT EXISTS embedding_records (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    chunk_id TEXT NOT NULL,
    provider_config_id TEXT,
    model TEXT NOT NULL,
    dims INTEGER NOT NULL DEFAULT 0,
    vector TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    UNIQUE (chunk_id, model)
  )`,
  `CREATE TABLE IF NOT EXISTS agent_actions (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    conversation_id TEXT,
    message_id TEXT,
    capability TEXT NOT NULL,
    action_type TEXT NOT NULL,
    params TEXT NOT NULL DEFAULT '{}',
    target TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'proposed',
    risk_level TEXT NOT NULL DEFAULT 'medium',
    policy_id TEXT,
    approval_request_id TEXT,
    result TEXT,
    error TEXT,
    executed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_agent_actions_ws_status ON agent_actions (workspace_id, status)`,
  `CREATE TABLE IF NOT EXISTS item_feedback (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    source_item_id TEXT,
    task_candidate_id TEXT,
    digest_item_id TEXT,
    kind TEXT NOT NULL,
    note TEXT,
    created_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_feedback_ws_created ON item_feedback (workspace_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL DEFAULT 'null',
    updated_at TEXT NOT NULL,
    UNIQUE (workspace_id, key)
  )`,
];

export async function up(db: Kysely<any>): Promise<void> {
  for (const stmt of STATEMENTS) {
    await sql.raw(stmt).execute(db);
  }
}

export async function down(db: Kysely<any>): Promise<void> {
  const tables = [
    'app_settings',
    'item_feedback',
    'agent_actions',
    'embedding_records',
    'retrieval_chunks',
    'llm_call_logs',
    'llm_task_routes',
    'llm_provider_configs',
    'connector_runs',
    'uploaded_files',
    'messages',
    'conversations',
    'audit_logs',
    'approval_requests',
    'permission_policies',
    'memory_entries',
    'user_preferences',
    'digest_items',
    'digests',
    'task_candidates',
    'projects',
    'organizations',
    'people',
    'source_attachments',
    'source_items',
    'source_accounts',
    'workspaces',
    'users',
  ];
  for (const t of tables) {
    await sql.raw(`DROP TABLE IF EXISTS ${t}`).execute(db);
  }
}
