/**
 * Shared machinery for the mock connectors.
 *
 * Cursor model (opaque strings, stable across runs):
 *  - `offset:<n>`  — mid-run paging position during a full sync.
 *  - `synced:<n>`  — persisted after a completed sync; `n` = how many items of
 *                    the combined [base..., incremental...] stream have been
 *                    seen. An incremental sync with `synced:<n>` returns only
 *                    items past position `n` — so the first incremental sync
 *                    after a full sync yields the 1–2 "new" arrivals from the
 *                    demo dataset, and the next one yields nothing.
 *
 * Time: the demo dataset is generated relative to "now". Mock connectors are
 * adapters simulating a live provider, so by default they use the current
 * wall clock; tests and the server can pin time deterministically by setting
 * `ctx.settings.demoNow` to an ISO string (or epoch ms).
 */
import type { RawSourceItem } from '@donna/core';
import type { ConnectorContext, SyncPage, SyncRequest } from '../types.js';

export const DEFAULT_PAGE_LIMIT = 50;

export function resolveDemoNow(ctx: ConnectorContext): Date {
  const v = ctx.settings['demoNow'];
  if (v instanceof Date && !Number.isNaN(v.getTime())) return v;
  if (typeof v === 'string' || typeof v === 'number') {
    const d = new Date(v);
    if (!Number.isNaN(d.getTime())) return d;
  }
  return new Date();
}

export interface MockCursor {
  kind: 'offset' | 'synced';
  position: number;
}

export function parseMockCursor(cursor: string | null | undefined): MockCursor | null {
  if (!cursor) return null;
  const match = /^(offset|synced):(\d+)$/.exec(cursor);
  if (!match) return null;
  const kind = match[1];
  const raw = match[2];
  if ((kind !== 'offset' && kind !== 'synced') || raw === undefined) return null;
  return { kind, position: Number(raw) };
}

/**
 * Serve one sync page from a base list plus simulated incremental arrivals.
 */
export function serveMockPage(
  base: RawSourceItem[],
  incremental: RawSourceItem[],
  req: SyncRequest,
): SyncPage {
  const limit = req.limit !== undefined && req.limit > 0 ? req.limit : DEFAULT_PAGE_LIMIT;
  const cursor = parseMockCursor(req.cursor);

  if (req.mode === 'incremental' && cursor?.kind === 'synced') {
    // Only items "newer" than the persisted position.
    const all = [...base, ...incremental];
    const start = Math.min(cursor.position, all.length);
    const items = all.slice(start, start + limit);
    const end = start + items.length;
    return { items, nextCursor: `synced:${end}`, done: end >= all.length };
  }

  // Full sync (or an incremental run that has no prior position): page
  // through the base dataset from the offset cursor.
  const start = cursor?.kind === 'offset' ? Math.min(cursor.position, base.length) : 0;
  const items = base.slice(start, start + limit);
  const end = start + items.length;
  const done = end >= base.length;
  return { items, nextCursor: done ? `synced:${end}` : `offset:${end}`, done };
}

export function findMockItem(
  base: RawSourceItem[],
  incremental: RawSourceItem[],
  externalId: string,
): RawSourceItem | null {
  return (
    base.find((i) => i.externalId === externalId) ??
    incremental.find((i) => i.externalId === externalId) ??
    null
  );
}

/** Stable fake attachment payload for demos. */
export function mockAttachmentContent(externalRef: string): Uint8Array {
  return new TextEncoder().encode(
    `Mock attachment content for ${externalRef} (demo data, generated by Donna's mock connectors).`,
  );
}
